//
// Created by cfrenkel on 1/5/19.
//

#ifndef EXCELLENTEAM_ELLA_C_DNA_CFRENKEL_ERROR_CODES_H
#define EXCELLENTEAM_ELLA_C_DNA_CFRENKEL_ERROR_CODES_H

enum ERROR_CODE
{
    INVALID_CHARACTER = 0, NOT_DIVIDE_3, OUT_OF_RANGE,
    INVALID_INDEX, NOT_FOUND_COAMMAND, INVALID_COMMAND,
    INVALID_NAME_SEQ, NOT_EXIST_SEQ, FILE_NOT_FOUND
};

#endif //EXCELLENTEAM_ELLA_C_DNA_CFRENKEL_ERROR_CODES_H
